name: Setup Environment

on:
  workflow_call:
    secrets:
      dvc-access-key-id:
        description: 'DVC access key ID'
        required: true
      dv-secret-access-key:
        description: 'DVC secret access key'
        required: true
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: poetry

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root

      - name: Install DVC
        uses: iterative/setup-dvc@v1

      - name: Configure GIT
        run: |
          git config --global user.email "perko.domen@gmail.com"
          git config --global user.name "perkzen"

      - name: Configure DVC
        run: |
          dvc remote modify origin --local access_key_id ${{ secrets.dvc-access-key-id }}
          dvc remote modify origin --local secret_access_key ${{ secrets.dvc-secret-access-key }}

      - name: DVC pull
        run: |
          dvc pull -r origin --force