name: Setup Environment

on:
  workflow_call:
    inputs:
      dvc_access_key_id:
        type: string
        required: true
      dvc_secret_access_key:
        type: string
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: poetry

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root

      - name: Install DVC
        uses: iterative/setup-dvc@v1

      - name: Configure GIT
        run: |
          git config --global user.email "perko.domen@gmail.com"
          git config --global user.name "perkzen"

      - name: Configure DVC
        run: |
          dvc remote modify origin --local access_key_id ${{ inputs.dvc_access_key_id }}
          dvc remote modify origin --local secret_access_key ${{ inputs.dvc_secret_access_key }}

      - name: DVC pull
        run: |
          dvc pull -r origin --force
